name: Compile LaTeX

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Alexx on top?'
        required: false
        default: 'YESSS'
        type: choice
        options:
          - 'YESSS'
          - 'nuUh!'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      #- name: Upload PDF file
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: PDF
      #    path: main.pdf